spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    # 引用项目中的文件
    url: jdbc:sqlite::resource:sqlite/sql
    username:
    password:

# Mybatis配置
mybatis:
  mapperLocations: classpath:mappers/*.xml